development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: decovich
  password: Fr0g&T0ad
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: decovich
  password: Fr0g&T0ad